version: "3"
services:
  api:
    image: node:12-alpine
    working_dir: /usr/src
    volumes:
      - .:/usr/src
    command: sh -c "yarn && npx ng serve api"
    ports:
      - 3333:3333
    environment:
      - NODE_ENV=development
      - PORT=3333
