steps:
  - name: node
    entrypoint: yarn
    args: ['install']
  - name: node
    entrypoint: npm
    args: [ 'run', 'lint', 'api' ]
  - name: node
    entrypoint: npm
    args: [ 'run', 'test', 'api' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/api', '-f', 'apps/api/Dockerfile', '.' ]
images:
  - 'gcr.io/$PROJECT_ID/api'
